# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7eda16f65788a0e4374263454df90bc8a7a4a6b437a1f0f7014d5ca3db4553cc531b5725768d27524e2d6a909ce85b3bc43bec765cd183006dd3d7b814f826d4

test:
  secret_key_base: 08cb982cbacc27569e6f4fa16d4c6ec6a1e29f607e55a8da587c6ee4118b91c1b848e88e1cadd6cd75a5ed47fbc2a86b7a00904f1053411820fe86f39cdbe7e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
